name: 'Mirror to BitBucket GitHub Action'
description: 'Mirrors a GitHub Git repository to BitBucket'
branding:
  icon: upload-cloud
  color: blue
inputs:
  username:
    required: true
    default: ${{ github.actor }}
  access_token:
    required: true
  repository:
    required: true
    default: ${{ github.event.repository.name }}
  spacename:
    required: true
    default: ${{ github.actor }}
  project_key:
    required: true
    default: ${{ github.actor }}

runs:
  using: "composite"
  steps:
    - run: chmod +x ${{ github.action_path }}/fillbucket.sh
      shell: bash
      
    - run: ${{ github.action_path }}/fillbucket.sh "${{ inputs.username }}" "${{ inputs.access_token }}" "${{ inputs.repository }}" "${{ inputs.spacename }}" "${{ inputs.project_key }}"
      shell: bash
