name: 'Mirror to BitBucket GitHub Action'
description: 'Mirrors a GitHub Git repository to BitBucket'
branding:
  icon: upload-cloud
  color: blue
inputs:
  username:
    required: true
    default: ${{ github.actor }}
  password:
    required: true
  repository:
    required: true
    default: ${{ github.event.repository.name }}
  spacename:
    required: true
    default: ${{ github.actor }}

runs:
  using: "composite"
  steps:
    - name: Set Execute Permissions
      run: |
        chmod +x ${{ github.action_path }}/fillbucket.sh
      shell: bash

    - name: Print Permissions
      run: |
        ls -l ${{ github.action_path }}/fillbucket.sh
      shell: bash

    - name: Run Script
      run: ${{ github.action_path }}/fillbucket.sh "${{ inputs.username }}" "${{ inputs.password }}" "${{ inputs.repository }}" "${{ inputs.spacename }}"
      shell: bash
